services:
  mongo:
    image: mongo
#    container_name: mongodb
    ports:
      - "27017:27017"

#  app:
#    buid: .
##    container_name: springbootapp
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATA_MONGODB_HOST=mongo
#      - SPRING_DATA_MONGODB_PORT=27017
#    depends_on:
#      - mongo