services:
  mongo:
    image: mongo-image
    ports:
      - "27017:27017"

  app:
    build: .
    image: storageservice-image
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-image
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - mongo-image